apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  sources: []
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    path: app
    repoURL: "https://github.com/joebui/argocd-deployment"
    targetRevision: main
  destination:
    namespace: dev
    server: "https://kubernetes.default.svc"
