apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-app
  namespace: argocd
spec:
  project: default
  sources: []
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    path: .
    repoURL: https://github.com/joebui/argocd-deployment
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values_dev.yaml
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
