apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
  source:
    path: .
    repoURL: https://github.com/joebui/argocd-helm
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      # parameters:
      #   - name: blueGreen.enabled
      #     value: "true"
  destination:
    namespace: default
    server: https://kubernetes.default.svc
