apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: traefik-gateway
    app.kubernetes.io/name: traefik-gateway
  name: traefik-gateway

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/instance: traefik-gateway
    app.kubernetes.io/name: traefik-gateway
  name: traefik-role
  namespace: traefik-gateway
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - configmaps
      - nodes
      - pods
      - secrets
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-account
  namespace: traefik-gateway
  labels:
    app.kubernetes.io/instance: traefik-gateway
    app.kubernetes.io/name: traefik-gateway

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-role-binding
  labels:
    app.kubernetes.io/instance: traefik-gateway
    app.kubernetes.io/name: traefik-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-role
subjects:
  - kind: ServiceAccount
    name: traefik-account
    namespace: traefik-gateway

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-gateway
  namespace: traefik-gateway
  labels:
    app.kubernetes.io/instance: traefik-gateway
    app.kubernetes.io/name: traefik-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-gateway
      app.kubernetes.io/name: traefik-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-gateway
        app.kubernetes.io/name: traefik-gateway
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          resources:
            requests:
              memory: "128Mi"
              cpu: "256m"
            limits:
              memory: "256Mi"
              cpu: "512m"
          args:
            - --api.insecure=true
            - --providers.kubernetesingress=true
            - --providers.kubernetesingress.namespaces=dev,stg,prod,traefik-gateway
            - --providers.kubernetesingress.ingressendpoint.publishedservice=traefik-gateway/traefik-gateway
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-gateway
  namespace: traefik-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web
      targetPort: web
      port: 80
  selector:
    app.kubernetes.io/instance: traefik-gateway
    app.kubernetes.io/name: traefik-gateway
